### ISSUE TITLE
PhantomJS not working on multiple OS

### ISSUE THREAD

**Issue by GPLamb** [nikhil-sarin/redback#197]
Have tried examples for data loading from Swift for GRB data on multi[ple OS -- Mac, Linux (Mint, Ubuntu, Android)
PhantomJS is installed and opened as per instructions in examples.
Each system returns an error -- can PhantomJS be replaced for web-scraping Swift data.

**Comment by nikhil-sarin** [comment]
Hey @GPLamb - yeah, this is in progress. It's more work than it otherwise appeared to be, but it will be done soon.

**Comment by nikhil-sarin** [comment]
@GPLamb could you try the following code block? You'd first need to update selenium via `pip install --upgrade selenium` 

Then in python, if you have Chrome installed. Try; 

`from selenium import webdriver`
`driver = webdriver.Chrome()`
`driver.get("https://www.google.com/")`


If google.com opens for you then there's an easier fix I can do instead.

**Comment by GPLamb** [comment]
It seems PhantomJS is now working, but I get:

You are downloading BAT and XRT data, you will need to truncate the data for some models.
Traceback (most recent call last):
  File "/home/gavin/redback/getting_data_with_redback.py", line 31, in <module>
    data = redback.get_data.get_bat_xrt_afterglow_data_from_swift(grb=GRB, data_mode="flux")
  File "/home/gavin/redback/redback/get_data/__init__.py", line 54, in get_bat_xrt_afterglow_data_from_swift
    return get_swift_data(grb=grb, transient_type='afterglow', data_mode=data_mode, instrument="BAT+XRT")
  File "/home/gavin/redback/redback/get_data/__init__.py", line 102, in get_swift_data
    return getter.get_data()
  File "/home/gavin/redback/redback/get_data/swift.py", line 161, in get_data
    return super(SwiftDataGetter, self).get_data()
  File "/home/gavin/redback/redback/get_data/getter.py", line 17, in get_data
    self.collect_data()
  File "/home/gavin/redback/redback/get_data/swift.py", line 190, in collect_data
    self.download_integrated_flux_data()
  File "/home/gavin/redback/redback/get_data/swift.py", line 224, in download_integrated_flux_data
    driver = fetch_driver()
  File "/home/gavin/redback/redback/utils.py", line 552, in fetch_driver
    return webdriver.PhantomJS()
AttributeError: module 'selenium.webdriver' has no attribute 'PhantomJS'

**Comment by nikhil-sarin** [comment]
@GPLamb can you try using pull request #198 - it should work for you.

**Comment by nikhil-sarin** [comment]
closing as fixed by #198
